version: "3.3"

services:
  nginx:
      container_name: ${APP_NAME}-nginx
      restart: always
      build:
        context: .
        dockerfile: docker/Nginx.Dockerfile
      ports:
        - ${APP_BACKEND_PORT}:80
      links:
        - fpm
        - nginx-frontend
      volumes:
        - ${APP_PATH}:${APP_PATH_DOCKER}
      depends_on:
        - fpm
        - nginx-frontend
      working_dir: ${APP_PATH_DOCKER}
  fpm:
      container_name: ${APP_NAME}-fpm
      restart: always
      working_dir: ${APP_PATH_DOCKER}
      build:
        context: .
        dockerfile: docker/Fpm.Dockerfile
      volumes:
        - ${APP_PATH}:${APP_PATH_DOCKER}
#      extra_hosts:
#        - "dockerhost:${LOCAL_IP}"
      links:
        - db
      environment:
        CONTAINER_ROLE: fpm
      command: php-fpm
  db:
    container_name: ${APP_NAME}-db
    image: mysql:5.7
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  composer:
    container_name: ${APP_NAME}-composer
    image: composer:1.9
    volumes:
      - ${APP_PATH}:${APP_PATH_DOCKER}
    working_dir: ${APP_PATH_DOCKER}
    command: composer install --ignore-platform-reqs
  queue:
    build:
      context: .
      dockerfile: docker/Queue.Dockerfile
    restart: always
    container_name: ${APP_NAME}-queue
    working_dir: ${APP_PATH_DOCKER}
    depends_on:
      - fpm
    volumes:
      - ${APP_PATH}:${APP_PATH_DOCKER}
    environment:
      CONTAINER_ROLE: queue
  nginx-frontend:
    container_name: ${APP_NAME}-nginx-frontend
    restart: always
    build:
      context: .
      dockerfile: docker/Frontend.Dockerfile
    working_dir: ${APP_PATH_DOCKER}

#  scheduler:
#    build:
#      context: .
#      dockerfile: docker/Queue.Dockerfile
#    restart: always
#    container_name: ${APP_NAME}-scheduler
#    working_dir: ${APP_PATH_DOCKER}
#    depends_on:
#      - fpm
#    volumes:
#      - ${APP_PATH}:${APP_PATH_DOCKER}
#    environment:
#      CONTAINER_ROLE: scheduler


