version: "3.4"

services:
  backend:
    container_name: ${APP_NAME}-backend
    restart: always
    working_dir: /var/www/app
    tty: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    ports:
      - ${APP_PORT}:80
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/var/www/app
    environment:
      WEB_DOCUMENT_ROOT: /var/www/app/public
      PHP_MEMORY_LIMIT: 64M
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      PHP_MAX_EXECUTION_TIME: 18000dc
      SERVICE_NGINX_CLIENT_MAX_BODY_SIZE: 100M
    networks:
      - app-network
  db:
    container_name: ${APP_NAME}-db
    image: mysql:5.7
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tager
      - TZ=${APP_TIMEZONE:-Europe/Minsk}
    networks:
      - app-network
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  redis:
    image: redis
    container_name: ${APP_NAME}-redis
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge


